---
# Jenkins Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 50000
    targetPort: 50000
    protocol: TCP
    name: agent
  selector:
    app: jenkins

---
# Alternative: NodePort Service (for testing without LoadBalancer costs)
apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 50000
    targetPort: 50000
    nodePort: 30050
    protocol: TCP
    name: agent
  selector:
    app: jenkins

