---
# Example Secrets for Application
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  # Database credentials
  DATABASE_USER: "appuser"
  DATABASE_PASSWORD: "AppPassword456"
  DATABASE_NAME: "myappdb"
  DATABASE_HOST: "mysql.default.svc.cluster.local"
  DATABASE_PORT: "3306"
  
  # Application secrets
  SESSION_SECRET: "your-random-session-secret-change-this"
  JWT_SECRET: "your-jwt-secret-key-change-this"
  API_KEY: "your-external-api-key-here"
  
  # External service credentials
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  
  # Email service
  SMTP_USERNAME: "your-smtp-username"
  SMTP_PASSWORD: "your-smtp-password"

---
# Example TLS Secret (for HTTPS)
# In production, use cert-manager or AWS ACM
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: default
type: kubernetes.io/tls
data:
  # These are example base64-encoded values
  # In production, use real certificates
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lKQUtIMGFxdzFyVzJLTUEwR0NTcUdTSWIzRFFFQkN3VUFNRVl4Q3pBSkJnTlYKQkFZVEFsVlRNUk13RVFZRFZRUUlEQXBEWVd4cFptOXlibWxoTVJZd0ZBWURWUVFIREExVGJtRnJaU0JQYVd3dApjbTl0TVEwd0N3WURWUVFEREFSMFpYTjBNQjRYRFRJek1ERXdNVEF3TURBd01Gb1hEVEkwTURFd01UQXdNREF3Ck1Gb3dSakVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnTUNrTmhiR2xtYjNKdWFXRXhGakFVQmdOVkJBY00KRFZOdVlXdGxJRTlwYkhScGIyMHhEVEFMQmdOVkJBTU1CSFJsYzNRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFEVzExQm5kS2tXWlBRREtmSzJVcFRmZDBOQ0F1Q1RNUW8xRkFBQUFBQUFBQUFBCkFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFcxMUJuZEtrV1pQUUQKS2ZLMlVwVGZkME5DQXVDVE1RbzFGQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQpBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBCkFBQUFBQT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=

---
# Example Docker Registry Secret
# Use this to pull images from private registries
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  # Create with: kubectl create secret docker-registry docker-registry-secret \
  #   --docker-server=your-registry-server \
  #   --docker-username=your-name \
  #   --docker-password=your-password \
  #   --docker-email=your-email
  .dockerconfigjson: eyJhdXRocyI6eyJ5b3VyLXJlZ2lzdHJ5LXNlcnZlciI6eyJ1c2VybmFtZSI6InlvdXItbmFtZSIsInBhc3N3b3JkIjoieW91ci1wYXNzd29yZCIsImVtYWlsIjoieW91ci1lbWFpbCIsImF1dGgiOiJlWFZ2ZFhJdGJtRnRaVHA1YjNWeUxYQmhjM04zYjNKayJ9fX0=

